version: '2'

services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "15672:15672"

  discovery:
    build: microservices/support/discovery-server
    restart: always
    ports:
      # HOST:CONTAINER
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker1
      - zone=NYC
    extra_hosts:
        # Knowing about the other node i.e. discovery2 is fine but knowing about itself not make any sense as JHipster registry works without this.
        - "discovery:192.168.1.6"
        - "discovery2:192.168.1.6"

  discovery2:
    build: microservices/support/discovery-server
    # Not necessary to have depends_on (Only add in case you run into image already exists issues)
    depends_on:
      - discovery
    restart: always
    ports:
      # HOST:CONTAINER
      - "8762:8762"
    environment:
      - SPRING_PROFILES_ACTIVE=docker2
      - zone=NC
    extra_hosts:
      # Knowing about the other node i.e. discovery is fine but knowing about itself not make any sense as JHipster registry works without this.
      - "discovery2:192.168.1.6"
      - "discovery:192.168.1.6"

  config:
    build: microservices/support/config-server
    restart: always
    ports:
      - "8888:8888"
    volumes:
      - $PWD/../blog-microservices-config:/config-repo

  auth:
    build: microservices/support/auth-server
    restart: always
    ports:
      - "9999:9999"

  turbine:
    build: microservices/support/turbine
    ports:
      - "8989:8989"
    volumes:
      - $PWD/logs:/logs    

  pro-nyc:
    build: microservices/core/product-service
    restart: always
    environment:
      - zone=NYC

  rec-nyc:
    build: microservices/core/recommendation-service
    restart: always
    environment:
      - zone=NYC

  rev-nyc:
    build: microservices/core/review-service
    restart: always
    environment:
      - zone=NYC

  composite-nyc:
    build: microservices/composite/product-composite-service
    restart: always
    environment:
      - zone=NYC

  pro-nc:
    build: microservices/core/product-service
    restart: always
    environment:
      - zone=NC

  rec-nc:
    build: microservices/core/recommendation-service
    restart: always
    environment:
      - zone=NC

  rev-nc:
    build: microservices/core/review-service
    restart: always
    environment:
      - zone=NC

  composite-nc:
    build: microservices/composite/product-composite-service
    restart: always
    environment:
      - zone=NC

  monitor:
    build: microservices/support/monitor-dashboard
    restart: always
    ports:
      - "7979:7979"

  edge-ny:
    build: microservices/support/edge-server
    restart: always
    ports:
      - "8443:8765"
    environment:
      - zone=NYC

  edge-nc:
    build: microservices/support/edge-server
    restart: always
    ports:
      - "9443:8765"
    environment:
      - zone=NC
