server:
  port: 8888
  ssl:
    key-store: classpath:server.jks
    key-store-password: password
    key-password: password

security.basic.enabled: false

# Configuration of a local Git-repo for development locally without Docker
# note that we are still using git; We just access the git-repo via file: protocol
spring.cloud.config.server.git.uri: file:///${PWD}/../../../../blog-microservices-config/

eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/

spring.rabbitmq:
  host: localhost
  port: 5672

logging:
  level:
    root: WARN
    se.callista: INFO

    org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: INFO
    org.apache.catalina.session.ManagerBase: INFO

    # Set INFO to see the allocated port
    org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer: INFO
    org.springframework.boot.context.embedded.undertow.UndertowEmbeddedServletContainer: INFO


---
# For deployment in Docker containers
spring:
  profiles: docker

security.basic.enabled: true

spring.rabbitmq.host: rabbitmq

# when running docker locally on a dev pc the config-repo is mounted to a local git-repo in docker-compose file
spring.cloud.config.server.git.uri: /config-repo

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/

